// =============================================================================
// File: ValidationFix.cs
// Project: Lexichord.Abstractions
// Description: Represents a suggested fix for a validation issue.
// =============================================================================
// LOGIC: Each fix describes a text replacement that can resolve a validation
//   finding or hallucination. Fixes with CanAutoApply=true and a valid
//   ReplaceSpan can be applied automatically by ValidateAndFixAsync.
//
// v0.6.6g: Post-Generation Validator (CKVS Phase 3b)
// Dependencies: TextSpan (v0.4.6e)
// =============================================================================

namespace Lexichord.Abstractions.Contracts.Knowledge.Copilot;

/// <summary>
/// Represents a suggested fix for a validation finding or hallucination.
/// </summary>
/// <remarks>
/// <para>
/// Fixes are generated by the <see cref="IPostGenerationValidator"/> from
/// validation findings and hallucination detections. Each fix describes a
/// text replacement that would resolve the issue.
/// </para>
/// <para>
/// <b>Auto-Apply Logic:</b>
/// <list type="bullet">
///   <item><see cref="CanAutoApply"/> is <c>true</c> when the fix has high
///     confidence (&gt; 0.9) and a valid <see cref="ReplaceSpan"/>.</item>
///   <item><see cref="IPostGenerationValidator.ValidateAndFixAsync"/> applies
///     only auto-applicable fixes.</item>
///   <item>Enterprise license tier required for auto-fix.</item>
/// </list>
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.6.6g as part of the Post-Generation Validator.
/// </para>
/// </remarks>
public record ValidationFix
{
    /// <summary>
    /// Human-readable description of the fix.
    /// </summary>
    /// <value>
    /// A concise explanation of what the fix does, e.g.,
    /// "Replace unsupported claim: GET /api/foo".
    /// </value>
    public required string Description { get; init; }

    /// <summary>
    /// The text span to replace in the generated content.
    /// </summary>
    /// <value>
    /// A <see cref="TextSpan"/> identifying the character range to replace,
    /// or <c>null</c> if the fix position is unknown.
    /// </value>
    /// <remarks>
    /// LOGIC: If null, the fix cannot be auto-applied and is advisory only.
    /// </remarks>
    public TextSpan? ReplaceSpan { get; init; }

    /// <summary>
    /// The replacement text.
    /// </summary>
    /// <value>
    /// The corrected text to substitute at <see cref="ReplaceSpan"/>, or
    /// <c>null</c> for deletion.
    /// </value>
    public string? ReplacementText { get; init; }

    /// <summary>
    /// Confidence in the fix (0–1).
    /// </summary>
    /// <value>
    /// A score from 0.0 (low confidence) to 1.0 (certain). Only fixes
    /// with confidence &gt; 0.9 are eligible for auto-apply.
    /// </value>
    public float Confidence { get; init; }

    /// <summary>
    /// Whether the fix can be applied automatically.
    /// </summary>
    /// <value>
    /// <c>true</c> if the fix has sufficient confidence and a valid
    /// <see cref="ReplaceSpan"/>; otherwise <c>false</c>.
    /// </value>
    /// <remarks>
    /// LOGIC: Auto-apply requires confidence &gt; 0.9 and a non-null
    /// <see cref="ReplaceSpan"/>. Enterprise license tier is also required.
    /// </remarks>
    public bool CanAutoApply { get; init; }
}
