// -----------------------------------------------------------------------
// <copyright file="FixSuggestion.cs" company="Lexichord">
//     Copyright (c) Lexichord. All rights reserved.
//     Licensed under the MIT License.
// </copyright>
// -----------------------------------------------------------------------

using Lexichord.Abstractions.Agents;

namespace Lexichord.Abstractions.Contracts.Agents;

/// <summary>
/// Represents a suggested fix for a style deviation, generated by AI with
/// confidence scoring, quality assessment, and visual diff.
/// </summary>
/// <remarks>
/// <para>
/// <b>LOGIC:</b> A <see cref="FixSuggestion"/> contains everything needed to
/// review and apply a fix for a style violation:
/// <list type="bullet">
///   <item><description>The original and suggested text</description></item>
///   <item><description>A visual diff showing changes</description></item>
///   <item><description>Confidence and quality scores</description></item>
///   <item><description>An explanation of the change</description></item>
///   <item><description>Alternative suggestions if available</description></item>
///   <item><description>Validation results if validated</description></item>
/// </list>
/// </para>
/// <para>
/// <b>High Confidence Fixes:</b> A fix is considered high-confidence when:
/// <list type="bullet">
///   <item><description>Confidence >= 0.9</description></item>
///   <item><description>Quality score >= 0.9</description></item>
///   <item><description>Validation passed with <see cref="ValidationStatus.Valid"/></description></item>
/// </list>
/// High-confidence fixes are candidates for automatic application without user review.
/// </para>
/// <para>
/// <b>Thread Safety:</b> This record is immutable and thread-safe.
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.7.5b as part of the Automatic Fix Suggestions feature.
/// </para>
/// </remarks>
public record FixSuggestion
{
    /// <summary>
    /// Unique identifier for this suggestion.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Generated at creation time. Used to track suggestions
    /// through the fix workflow and for learning loop feedback.
    /// </remarks>
    public required Guid SuggestionId { get; init; }

    /// <summary>
    /// The deviation this suggestion addresses.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Links back to the <see cref="StyleDeviation.DeviationId"/>
    /// that this fix was generated for.
    /// </remarks>
    public required Guid DeviationId { get; init; }

    /// <summary>
    /// The original text with the violation.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> The text that will be replaced when the fix is applied.
    /// Corresponds to <see cref="StyleDeviation.OriginalText"/>.
    /// </remarks>
    public required string OriginalText { get; init; }

    /// <summary>
    /// The suggested replacement text.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> The AI-generated text that resolves the style violation.
    /// Applying this text should resolve the violation without introducing new issues.
    /// </remarks>
    public required string SuggestedText { get; init; }

    /// <summary>
    /// Human-readable explanation of the change.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> The LLM provides an explanation of:
    /// <list type="bullet">
    ///   <item><description>What specific change was made</description></item>
    ///   <item><description>Why this change resolves the violation</description></item>
    ///   <item><description>Any trade-offs or considerations</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Explanations help users understand the fix and make informed decisions.
    /// </para>
    /// </remarks>
    public required string Explanation { get; init; }

    /// <summary>
    /// Confidence score for the suggestion (0.0 to 1.0).
    /// </summary>
    /// <value>Default: 0.8.</value>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> Combines multiple signals to estimate fix reliability:
    /// <list type="bullet">
    ///   <item><description>LLM's self-reported confidence</description></item>
    ///   <item><description>Learning context (past acceptance rates)</description></item>
    ///   <item><description>Validation results</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Higher confidence indicates a more reliable fix. Values below 0.7 should
    /// be flagged for careful user review.
    /// </para>
    /// </remarks>
    public double Confidence { get; init; } = 0.8;

    /// <summary>
    /// Quality score based on semantic preservation (0.0 to 1.0).
    /// </summary>
    /// <value>Default: 0.8.</value>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> Measures how well the fix preserves the original meaning:
    /// <list type="bullet">
    ///   <item><description>Semantic similarity between original and suggested text</description></item>
    ///   <item><description>Length change penalties</description></item>
    ///   <item><description>Word overlap analysis</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Higher quality indicates better meaning preservation. Low quality scores
    /// may indicate the fix significantly alters the original intent.
    /// </para>
    /// </remarks>
    public double QualityScore { get; init; } = 0.8;

    /// <summary>
    /// The diff showing changes between original and suggested text.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Generated using DiffPlex to provide visual representation
    /// of changes for review in the UI.
    /// </remarks>
    public required TextDiff Diff { get; init; }

    /// <summary>
    /// Token usage for this suggestion generation.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Tracks LLM resource consumption for cost tracking and
    /// usage analytics.
    /// </remarks>
    public UsageMetrics? TokenUsage { get; init; }

    /// <summary>
    /// Time taken to generate this suggestion.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Measures end-to-end generation time including prompt
    /// construction, LLM call, response parsing, and validation.
    /// </remarks>
    public TimeSpan GenerationTime { get; init; }

    /// <summary>
    /// Alternative suggestions if available.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> The LLM may provide multiple valid fixes. Alternatives
    /// are ordered by descending confidence and allow users to choose the
    /// most appropriate fix for their context.
    /// </para>
    /// <para>
    /// The number of alternatives is controlled by
    /// <see cref="FixGenerationOptions.MaxAlternatives"/>.
    /// </para>
    /// </remarks>
    public IReadOnlyList<AlternativeSuggestion>? Alternatives { get; init; }

    /// <summary>
    /// Whether validation has been performed on this suggestion.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Set to <c>true</c> when <see cref="FixGenerationOptions.ValidateFixes"/>
    /// is enabled and validation completed successfully.
    /// </remarks>
    public bool IsValidated { get; init; }

    /// <summary>
    /// Validation result if validated.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Contains detailed validation information including whether
    /// the fix resolves the violation and any new violations introduced.
    /// </remarks>
    public FixValidationResult? ValidationResult { get; init; }

    /// <summary>
    /// Whether this is a high-confidence automated fix.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> A fix is high-confidence when ALL of these conditions are met:
    /// <list type="bullet">
    ///   <item><description>Confidence >= 0.9</description></item>
    ///   <item><description>Quality score >= 0.9</description></item>
    ///   <item><description>Fix has been validated</description></item>
    ///   <item><description>Validation status is <see cref="ValidationStatus.Valid"/></description></item>
    /// </list>
    /// </para>
    /// <para>
    /// High-confidence fixes are candidates for "Apply All" or auto-fix features.
    /// </para>
    /// </remarks>
    public bool IsHighConfidence =>
        Confidence >= 0.9 &&
        QualityScore >= 0.9 &&
        IsValidated &&
        ValidationResult?.Status == ValidationStatus.Valid;

    /// <summary>
    /// Error message if generation failed.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Contains the error message when fix generation fails.
    /// When this is set, <see cref="Success"/> returns <c>false</c>.
    /// </remarks>
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// Whether the suggestion was successfully generated.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Returns <c>true</c> if <see cref="ErrorMessage"/> is null
    /// or empty, indicating successful generation.
    /// </remarks>
    public bool Success => string.IsNullOrEmpty(ErrorMessage);

    /// <summary>
    /// Creates a failed suggestion with an error message.
    /// </summary>
    /// <param name="deviationId">The ID of the deviation that failed to fix.</param>
    /// <param name="originalText">The original text that could not be fixed.</param>
    /// <param name="error">The error message describing the failure.</param>
    /// <returns>A <see cref="FixSuggestion"/> representing a failed generation attempt.</returns>
    /// <remarks>
    /// <para>
    /// <b>LOGIC:</b> Factory method for creating error responses. The suggested
    /// text is set to the original (no change) and scores are set to zero.
    /// </para>
    /// </remarks>
    public static FixSuggestion Failed(Guid deviationId, string originalText, string error) => new()
    {
        SuggestionId = Guid.NewGuid(),
        DeviationId = deviationId,
        OriginalText = originalText,
        SuggestedText = originalText, // Unchanged
        Explanation = $"Generation failed: {error}",
        ErrorMessage = error,
        Confidence = 0,
        QualityScore = 0,
        Diff = TextDiff.Empty
    };

    /// <summary>
    /// Creates a suggestion indicating a license is required.
    /// </summary>
    /// <param name="deviationId">The ID of the deviation.</param>
    /// <param name="originalText">The original text.</param>
    /// <returns>A <see cref="FixSuggestion"/> indicating license requirement.</returns>
    /// <remarks>
    /// <b>LOGIC:</b> Factory method for creating license-gated error responses
    /// when the user doesn't have the required WriterPro tier.
    /// </remarks>
    public static FixSuggestion LicenseRequired(Guid deviationId, string originalText) =>
        Failed(deviationId, originalText, "Writer Pro license required for fix generation.");
}
