// -----------------------------------------------------------------------
// <copyright file="StyleDeviation.cs" company="Lexichord">
//     Copyright (c) Lexichord. All rights reserved.
//     Licensed under the MIT License.
// </copyright>
// -----------------------------------------------------------------------

using Lexichord.Abstractions.Contracts.Editor;

namespace Lexichord.Abstractions.Contracts.Agents;

/// <summary>
/// Represents a single style deviation detected in a document, enriched with
/// context information needed for AI-powered fix generation.
/// </summary>
/// <remarks>
/// <para>
/// <b>LOGIC:</b> StyleDeviation wraps a raw <see cref="StyleViolation"/> with additional
/// context that the Tuning Agent needs to generate intelligent fixes:
/// <list type="bullet">
///   <item><description>Surrounding text for AI understanding of context</description></item>
///   <item><description>Auto-fixability classification based on rule characteristics</description></item>
///   <item><description>Priority mapping from severity for review ordering</description></item>
///   <item><description>Complete rule details for fix generation prompts</description></item>
/// </list>
/// </para>
/// <para>
/// <b>Thread Safety:</b> This record is immutable and thread-safe.
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.7.5a as part of the Style Deviation Scanner feature.
/// </para>
/// </remarks>
public record StyleDeviation
{
    /// <summary>
    /// Unique identifier for this deviation instance.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Generated by the scanner at creation time. Used for tracking
    /// individual deviations through the fix workflow.
    /// </remarks>
    public required Guid DeviationId { get; init; }

    /// <summary>
    /// The underlying style violation from the linting system.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Contains the raw violation data including message, position,
    /// and matched text. Sourced from <see cref="StyleRule.FindViolationsAsync"/>.
    /// </remarks>
    public required StyleViolation Violation { get; init; }

    /// <summary>
    /// The text span where the deviation occurs in the document.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Derived from the violation's start/end offsets. Used for
    /// position-preserving text replacements during fix application.
    /// </remarks>
    public required TextSpan Location { get; init; }

    /// <summary>
    /// The original text that contains the violation.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Extracted from the document at the violation location.
    /// This is the text that will be replaced when a fix is applied.
    /// </remarks>
    public required string OriginalText { get; init; }

    /// <summary>
    /// Surrounding context for AI analysis, typically including text before
    /// and after the violation.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Extracted with a configurable window size (default 500 chars).
    /// The context helps the AI understand:
    /// <list type="bullet">
    ///   <item><description>Document tone and style</description></item>
    ///   <item><description>Paragraph/sentence structure</description></item>
    ///   <item><description>Related terminology</description></item>
    /// </list>
    /// </remarks>
    public required string SurroundingContext { get; init; }

    /// <summary>
    /// The style rule that was violated, containing rule details needed for
    /// fix generation prompts.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Provides the AI with:
    /// <list type="bullet">
    ///   <item><description>Rule name and description</description></item>
    ///   <item><description>Category for context</description></item>
    ///   <item><description>Suggestion text if available</description></item>
    /// </list>
    /// </remarks>
    public required StyleRule ViolatedRule { get; init; }

    /// <summary>
    /// Whether this deviation can be automatically fixed by AI.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Determined by the scanner based on rule characteristics:
    /// <list type="bullet">
    ///   <item><description>Pattern-based rules (terminology) → auto-fixable</description></item>
    ///   <item><description>Rules with suggestions → auto-fixable</description></item>
    ///   <item><description>Grammar/readability rules → auto-fixable</description></item>
    ///   <item><description>Structure/formatting rules → manual-only</description></item>
    ///   <item><description>High-complexity rules → manual-only</description></item>
    /// </list>
    /// Default is <c>true</c>; the scanner sets to <c>false</c> when appropriate.
    /// </remarks>
    public bool IsAutoFixable { get; init; } = true;

    /// <summary>
    /// Priority for fixing based on rule severity and impact.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Mapped from <see cref="ViolationSeverity"/>:
    /// Error→Critical, Warning→High, Info→Normal, Hint→Low.
    /// Used for ordering deviations in the review UI.
    /// </remarks>
    public DeviationPriority Priority { get; init; } = DeviationPriority.Normal;

    /// <summary>
    /// Gets the category of the deviation for grouping in UI.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Derived from <see cref="ViolatedRule"/>.<see cref="StyleRule.Category"/>.
    /// Returns the enum name as a string for display purposes.
    /// </remarks>
    public string Category => ViolatedRule.Category.ToString();

    /// <summary>
    /// Gets the rule ID for quick reference.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Delegates to <see cref="ViolatedRule"/>.<see cref="StyleRule.Id"/>.
    /// </remarks>
    public string RuleId => ViolatedRule.Id;

    /// <summary>
    /// Gets the human-readable message describing the violation.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Delegates to <see cref="Violation"/>.<see cref="StyleViolation.Message"/>.
    /// </remarks>
    public string Message => Violation.Message;

    /// <summary>
    /// Gets the suggested fix from the linter, if available.
    /// </summary>
    /// <remarks>
    /// <b>LOGIC:</b> Delegates to <see cref="Violation"/>.<see cref="StyleViolation.Suggestion"/>.
    /// May be <c>null</c> if the linter doesn't provide suggestions for this rule.
    /// </remarks>
    public string? LinterSuggestedFix => Violation.Suggestion;
}
