using Dapper.Contrib.Extensions;

namespace Lexichord.Abstractions.Entities;

/// <summary>
/// User entity representing a Lexichord user account.
/// </summary>
/// <remarks>
/// LOGIC: Users are identified by a UUID primary key for distributed systems compatibility.
/// The Email field is unique and serves as the login identifier.
/// PasswordHash is nullable to support OAuth-only authentication flows.
///
/// Mapping:
/// - Table: "Users"
/// - Primary Key: Id (UUID, auto-generated by database)
/// - Unique: Email
/// </remarks>
[Table("Users")]
public record User : EntityBase
{
    /// <summary>
    /// Unique identifier for the user.
    /// </summary>
    /// <remarks>
    /// UUID primary key generated by database using gen_random_uuid().
    /// [ExplicitKey] indicates this is the PK but NOT auto-increment.
    /// </remarks>
    [ExplicitKey]
    public Guid Id { get; init; }

    /// <summary>
    /// User's email address (unique, used for login).
    /// </summary>
    public required string Email { get; init; }

    /// <summary>
    /// Display name shown in the UI.
    /// </summary>
    public required string DisplayName { get; init; }

    /// <summary>
    /// Hashed password (null for OAuth-only users).
    /// </summary>
    /// <remarks>Uses bcrypt hashing with work factor 12.</remarks>
    public string? PasswordHash { get; init; }

    /// <summary>
    /// Whether the user account is active.
    /// </summary>
    /// <remarks>
    /// Inactive users cannot log in but their data is preserved.
    /// This enables soft-delete functionality.
    /// </remarks>
    public bool IsActive { get; init; } = true;
}
