// -----------------------------------------------------------------------
// <copyright file="PromptSuggestion.cs" company="Lexichord">
//     Copyright (c) Lexichord. All rights reserved.
//     Licensed under the MIT License.
// </copyright>
// -----------------------------------------------------------------------

namespace Lexichord.Modules.Agents.Models;

/// <summary>
/// Represents a prompt suggestion for the current document context.
/// </summary>
/// <remarks>
/// <para>
/// Generated by <see cref="Services.ContextAwarePromptSelector"/> based on the
/// document structure at the cursor position. Each suggestion maps to a prompt
/// template that can be rendered and sent to the Co-pilot agent.
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.6.7c as part of the Document-Aware Prompting feature.
/// </para>
/// </remarks>
/// <param name="Label">The display label shown to the user (e.g., "Improve writing").</param>
/// <param name="TemplateId">The ID of the prompt template to use when this suggestion is selected.</param>
public record PromptSuggestion(string Label, string TemplateId);
