// =============================================================================
// File: ClaimDataModelTests.cs
// Project: Lexichord.Tests.Unit
// Description: Unit tests for v0.5.6e Claim Data Model records and enums.
// =============================================================================
// LOGIC: Comprehensive tests covering record instantiation, factory methods,
//   canonical form generation, entity resolution, and predicate inverse lookup.
//
// v0.5.6e: Claim Data Model (CKVS Phase 2b)
// =============================================================================

using FluentAssertions;
using Lexichord.Abstractions.Contracts;
using Lexichord.Abstractions.Contracts.Knowledge.Claims;
using Xunit;

namespace Lexichord.Tests.Unit.Contracts.Knowledge.Claims;

[Trait("Category", "Unit")]
[Trait("Feature", "v0.5.6e")]
public class ClaimDataModelTests
{
    // =========================================================================
    // Claim Tests
    // =========================================================================

    [Fact]
    public void Claim_Creation_SetsRequiredProperties()
    {
        // Arrange
        var subject = ClaimEntity.Unresolved("/api/users", "Endpoint", 4, 14);
        var objectEntity = ClaimEntity.Unresolved("limit", "Parameter", 23, 28);

        // Act
        var claim = new Claim
        {
            Subject = subject,
            Predicate = ClaimPredicate.ACCEPTS,
            Object = ClaimObject.FromEntity(objectEntity),
            Confidence = 0.92f,
            DocumentId = Guid.NewGuid()
        };

        // Assert
        claim.Subject.Should().Be(subject);
        claim.Predicate.Should().Be(ClaimPredicate.ACCEPTS);
        claim.Object.Type.Should().Be(ClaimObjectType.Entity);
        claim.Confidence.Should().BeApproximately(0.92f, 0.001f);
        claim.ValidationStatus.Should().Be(ClaimValidationStatus.Pending);
        claim.IsActive.Should().BeTrue();
        claim.Version.Should().Be(1);
    }

    [Fact]
    public void Claim_Id_AutoGenerated()
    {
        // Arrange & Act
        var claim1 = new Claim
        {
            Subject = ClaimEntity.Unresolved("A", "Concept", 0, 1),
            Predicate = ClaimPredicate.HAS_PROPERTY,
            Object = ClaimObject.FromString("value")
        };
        var claim2 = new Claim
        {
            Subject = ClaimEntity.Unresolved("B", "Concept", 0, 1),
            Predicate = ClaimPredicate.HAS_PROPERTY,
            Object = ClaimObject.FromString("value")
        };

        // Assert
        claim1.Id.Should().NotBeEmpty();
        claim2.Id.Should().NotBeEmpty();
        claim1.Id.Should().NotBe(claim2.Id);
    }

    [Fact]
    public void Claim_ToCanonicalForm_ReturnsExpectedFormat()
    {
        // Arrange
        var subject = ClaimEntity.Unresolved("/api/users", "Endpoint", 0, 10);
        var objectEntity = ClaimEntity.Unresolved("limit", "Parameter", 20, 25);
        var claim = new Claim
        {
            Subject = subject,
            Predicate = ClaimPredicate.ACCEPTS,
            Object = ClaimObject.FromEntity(objectEntity)
        };

        // Act
        var canonical = claim.ToCanonicalForm();

        // Assert
        canonical.Should().Be("endpoint:/api/users ACCEPTS parameter:limit");
    }

    [Fact]
    public void Claim_ToCanonicalForm_WithLiteralObject_ReturnsCorrectFormat()
    {
        // Arrange
        var subject = ClaimEntity.Unresolved("limit", "Parameter", 0, 5);
        var claim = new Claim
        {
            Subject = subject,
            Predicate = ClaimPredicate.HAS_DEFAULT,
            Object = ClaimObject.FromInt(100, "requests/minute")
        };

        // Act
        var canonical = claim.ToCanonicalForm();

        // Assert
        canonical.Should().Be("parameter:limit HAS_DEFAULT 100 requests/minute");
    }

    // =========================================================================
    // ClaimEntity Tests
    // =========================================================================

    [Fact]
    public void ClaimEntity_Unresolved_CreatesUnlinkedEntity()
    {
        // Act
        var entity = ClaimEntity.Unresolved(
            surfaceForm: "/api/users",
            entityType: "Endpoint",
            startOffset: 4,
            endOffset: 14);

        // Assert
        entity.SurfaceForm.Should().Be("/api/users");
        entity.EntityType.Should().Be("Endpoint");
        entity.NormalizedForm.Should().Be("/api/users");
        entity.StartOffset.Should().Be(4);
        entity.EndOffset.Should().Be(14);
        entity.IsResolved.Should().BeFalse();
        entity.EntityId.Should().BeNull();
        entity.ResolvedEntity.Should().BeNull();
    }

    [Fact]
    public void ClaimEntity_Unresolved_WithCustomNormalizedForm_UsesProvidedForm()
    {
        // Act
        var entity = ClaimEntity.Unresolved(
            surfaceForm: "The Users Endpoint",
            entityType: "Endpoint",
            startOffset: 0,
            endOffset: 18,
            normalizedForm: "users_endpoint");

        // Assert
        entity.SurfaceForm.Should().Be("The Users Endpoint");
        entity.NormalizedForm.Should().Be("users_endpoint");
    }

    [Fact]
    public void ClaimEntity_Resolved_CreatesLinkedEntity()
    {
        // Arrange
        var knowledgeEntity = new KnowledgeEntity
        {
            Type = "Endpoint",
            Name = "GET /api/users"
        };

        // Act
        var entity = ClaimEntity.Resolved(
            surfaceForm: "the /api/users endpoint",
            entity: knowledgeEntity,
            confidence: 0.95f,
            startOffset: 4,
            endOffset: 27);

        // Assert
        entity.IsResolved.Should().BeTrue();
        entity.EntityId.Should().Be(knowledgeEntity.Id);
        entity.EntityType.Should().Be("Endpoint");
        entity.NormalizedForm.Should().Be("get /api/users");
        entity.ResolvedEntity.Should().Be(knowledgeEntity);
        entity.LinkingConfidence.Should().BeApproximately(0.95f, 0.001f);
    }

    [Fact]
    public void ClaimEntity_Resolved_ThrowsForNullEntity()
    {
        // Act & Assert
        var act = () => ClaimEntity.Resolved(
            surfaceForm: "test",
            entity: null!,
            confidence: 1.0f,
            startOffset: 0,
            endOffset: 4);

        act.Should().Throw<ArgumentNullException>();
    }

    // =========================================================================
    // ClaimObject Tests
    // =========================================================================

    [Fact]
    public void ClaimObject_FromEntity_CreatesEntityObject()
    {
        // Arrange
        var entity = ClaimEntity.Unresolved("limit", "Parameter", 0, 5);

        // Act
        var obj = ClaimObject.FromEntity(entity);

        // Assert
        obj.Type.Should().Be(ClaimObjectType.Entity);
        obj.Entity.Should().Be(entity);
        obj.LiteralValue.Should().BeNull();
        obj.LiteralType.Should().BeNull();
    }

    [Fact]
    public void ClaimObject_FromEntity_ThrowsForNullEntity()
    {
        // Act & Assert
        var act = () => ClaimObject.FromEntity(null!);
        act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void ClaimObject_FromString_CreatesStringLiteral()
    {
        // Act
        var obj = ClaimObject.FromString("application/json");

        // Assert
        obj.Type.Should().Be(ClaimObjectType.Literal);
        obj.LiteralValue.Should().Be("application/json");
        obj.LiteralType.Should().Be("string");
        obj.Entity.Should().BeNull();
    }

    [Fact]
    public void ClaimObject_FromInt_CreatesIntLiteral()
    {
        // Act
        var obj = ClaimObject.FromInt(100, "requests/minute");

        // Assert
        obj.Type.Should().Be(ClaimObjectType.Literal);
        obj.LiteralValue.Should().Be("100");
        obj.LiteralType.Should().Be("int");
        obj.Unit.Should().Be("requests/minute");
    }

    [Fact]
    public void ClaimObject_FromDecimal_CreatesDecimalLiteral()
    {
        // Act
        var obj = ClaimObject.FromDecimal(99.9m, "percent");

        // Assert
        obj.Type.Should().Be(ClaimObjectType.Literal);
        obj.LiteralValue.Should().Be("99.9");
        obj.LiteralType.Should().Be("decimal");
        obj.Unit.Should().Be("percent");
    }

    [Fact]
    public void ClaimObject_FromBool_CreatesBoolLiteral()
    {
        // Act
        var objTrue = ClaimObject.FromBool(true);
        var objFalse = ClaimObject.FromBool(false);

        // Assert
        objTrue.LiteralValue.Should().Be("true");
        objFalse.LiteralValue.Should().Be("false");
        objTrue.LiteralType.Should().Be("bool");
    }

    [Fact]
    public void ClaimObject_ToCanonicalForm_EntityReturnsNormalizedForm()
    {
        // Arrange
        var entity = ClaimEntity.Unresolved("limit", "Parameter", 0, 5);
        var obj = ClaimObject.FromEntity(entity);

        // Act
        var canonical = obj.ToCanonicalForm();

        // Assert
        canonical.Should().Be("limit");
    }

    [Fact]
    public void ClaimObject_ToCanonicalForm_LiteralWithUnit_IncludesUnit()
    {
        // Arrange
        var obj = ClaimObject.FromInt(100, "ms");

        // Act
        var canonical = obj.ToCanonicalForm();

        // Assert
        canonical.Should().Be("100 ms");
    }

    // =========================================================================
    // ClaimPredicate Tests
    // =========================================================================

    [Fact]
    public void ClaimPredicate_GetInverse_ReturnsCorrectInverse()
    {
        // Act & Assert
        ClaimPredicate.GetInverse(ClaimPredicate.CONTAINS).Should().Be(ClaimPredicate.BELONGS_TO);
        ClaimPredicate.GetInverse(ClaimPredicate.BELONGS_TO).Should().Be(ClaimPredicate.CONTAINS);
        ClaimPredicate.GetInverse(ClaimPredicate.ACCEPTS).Should().Be(ClaimPredicate.ACCEPTED_BY);
        ClaimPredicate.GetInverse(ClaimPredicate.RETURNS).Should().Be(ClaimPredicate.RETURNED_BY);
    }

    [Fact]
    public void ClaimPredicate_GetInverse_ReturnsNullForNoInverse()
    {
        // Act & Assert
        ClaimPredicate.GetInverse(ClaimPredicate.HAS_PROPERTY).Should().BeNull();
        ClaimPredicate.GetInverse(ClaimPredicate.HAS_DEFAULT).Should().BeNull();
        ClaimPredicate.GetInverse(ClaimPredicate.IS_DEPRECATED).Should().BeNull();
        ClaimPredicate.GetInverse("UNKNOWN_PREDICATE").Should().BeNull();
    }

    [Fact]
    public void ClaimPredicate_All_ContainsAllPredicates()
    {
        // Assert
        ClaimPredicate.All.Should().Contain(ClaimPredicate.CONTAINS);
        ClaimPredicate.All.Should().Contain(ClaimPredicate.ACCEPTS);
        ClaimPredicate.All.Should().Contain(ClaimPredicate.RETURNS);
        ClaimPredicate.All.Should().Contain(ClaimPredicate.HAS_PROPERTY);
        ClaimPredicate.All.Should().HaveCountGreaterOrEqualTo(20);
    }

    // =========================================================================
    // ClaimExtractionResult Tests
    // =========================================================================

    [Fact]
    public void ClaimExtractionResult_Empty_ReturnsEmptyResult()
    {
        // Act
        var result = ClaimExtractionResult.Empty;

        // Assert
        result.Claims.Should().BeEmpty();
        result.HasClaims.Should().BeFalse();
        result.HasFailures.Should().BeFalse();
        result.FailedSentences.Should().BeEmpty();
    }

    [Fact]
    public void ClaimExtractionResult_HasClaims_ReturnsTrueWhenPopulated()
    {
        // Arrange
        var claim = new Claim
        {
            Subject = ClaimEntity.Unresolved("A", "Concept", 0, 1),
            Predicate = ClaimPredicate.HAS_PROPERTY,
            Object = ClaimObject.FromString("value")
        };

        // Act
        var result = new ClaimExtractionResult
        {
            Claims = [claim],
            DocumentId = Guid.NewGuid()
        };

        // Assert
        result.HasClaims.Should().BeTrue();
        result.Claims.Should().HaveCount(1);
    }

    // =========================================================================
    // ClaimEvidence Tests
    // =========================================================================

    [Fact]
    public void ClaimEvidence_Length_ComputedCorrectly()
    {
        // Arrange
        var evidence = new ClaimEvidence
        {
            Sentence = "The endpoint accepts a parameter.",
            StartOffset = 100,
            EndOffset = 133
        };

        // Act & Assert
        evidence.Length.Should().Be(33);
    }

    // =========================================================================
    // ClaimRelation Tests
    // =========================================================================

    [Fact]
    public void ClaimRelation_DefaultConfidence_IsOne()
    {
        // Arrange & Act
        var relation = new ClaimRelation
        {
            RelatedClaimId = Guid.NewGuid(),
            RelationType = ClaimRelationType.Supports
        };

        // Assert
        relation.Confidence.Should().Be(1.0f);
    }
}
