// =============================================================================
// File: HighlightType.cs
// Project: Lexichord.Abstractions
// Description: Enum defining types of highlighting for matched content in snippets.
// =============================================================================
// LOGIC: Defines the semantic meaning of highlighted regions within snippets.
//   - Ordered by specificity (lower value = more specific match).
//   - Used by HighlightSpan to classify match types.
//   - Merge logic prefers more specific types when combining overlapping spans.
// =============================================================================
// VERSION: v0.5.6a (Snippet Extraction)
// =============================================================================

namespace Lexichord.Abstractions.Contracts;

/// <summary>
/// Types of highlighting for matched content within snippets.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="HighlightType"/> classifies the nature of a match within a snippet,
/// enabling UI components to apply different visual treatments based on match quality.
/// </para>
/// <para>
/// <b>Ordering:</b> Values are ordered by specificity, with lower values representing
/// more specific (exact) matches. When merging overlapping <see cref="HighlightSpan"/>
/// instances, the more specific type (lower value) is preserved.
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.5.6a as part of The Answer Preview feature.
/// </para>
/// </remarks>
public enum HighlightType
{
    /// <summary>
    /// Exact case-insensitive match of a query term.
    /// </summary>
    /// <remarks>
    /// The highest priority highlight type. Applied when the snippet text
    /// contains an exact (case-insensitive) match of a query keyword.
    /// </remarks>
    QueryMatch = 0,

    /// <summary>
    /// Fuzzy or approximate match of a query term.
    /// </summary>
    /// <remarks>
    /// Applied when the snippet text contains an approximate match of a query
    /// keyword (e.g., within edit distance of 2, or matching stemmed form).
    /// </remarks>
    FuzzyMatch = 1,

    /// <summary>
    /// Key phrase identified by natural language processing (future).
    /// </summary>
    /// <remarks>
    /// Reserved for future NLP-based key phrase extraction. Not currently
    /// generated by the snippet extraction pipeline.
    /// </remarks>
    KeyPhrase = 2,

    /// <summary>
    /// Named entity recognized in content (future).
    /// </summary>
    /// <remarks>
    /// Reserved for future named entity recognition. Not currently generated
    /// by the snippet extraction pipeline.
    /// </remarks>
    Entity = 3
}
