// =============================================================================
// File: IngestionQueueItem.cs
// Project: Lexichord.Abstractions
// Description: Represents an item in the ingestion queue awaiting processing.
// =============================================================================
// LOGIC: Immutable record representing a file queued for ingestion.
//   - Priority enables ordering (0 = highest priority).
//   - CorrelationId enables request tracing across the pipeline.
//   - EnqueuedAt tracks queue latency for monitoring.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.Ingestion;

/// <summary>
/// Represents an item in the ingestion queue awaiting processing.
/// </summary>
/// <remarks>
/// <para>
/// Queue items are immutable records that capture all information needed
/// to process a file through the ingestion pipeline. The <see cref="Priority"/>
/// field enables priority-based ordering where lower values are processed first.
/// </para>
/// <para>
/// <b>Priority Semantics:</b>
/// </para>
/// <list type="bullet">
///   <item><description><c>0</c>: Highest priority (user-initiated actions)</description></item>
///   <item><description><c>1</c>: High priority (recent file changes)</description></item>
///   <item><description><c>2</c>: Normal priority (batch operations)</description></item>
///   <item><description><c>3+</c>: Low priority (background indexing)</description></item>
/// </list>
/// <para>
/// <b>Correlation:</b> The <see cref="CorrelationId"/> field enables end-to-end
/// tracing of a file through the ingestion pipeline. If not provided, a new
/// correlation ID should be generated by the queue implementation.
/// </para>
/// </remarks>
/// <param name="Id">Unique identifier for this queue item.</param>
/// <param name="ProjectId">The project to associate the ingested document with.</param>
/// <param name="FilePath">Absolute path to the file to ingest.</param>
/// <param name="Priority">
/// Processing priority where lower values are processed first.
/// Default is <c>2</c> (normal priority).
/// </param>
/// <param name="EnqueuedAt">
/// Timestamp when the item was added to the queue.
/// Used for latency monitoring and duplicate detection windowing.
/// </param>
/// <param name="CorrelationId">
/// Optional correlation identifier for request tracing.
/// If null, a unique ID is generated when the item is enqueued.
/// </param>
public sealed record IngestionQueueItem(
    Guid Id,
    Guid ProjectId,
    string FilePath,
    int Priority,
    DateTimeOffset EnqueuedAt,
    string? CorrelationId = null)
{
    /// <summary>
    /// Priority value for user-initiated actions (highest priority).
    /// </summary>
    public const int PriorityUserAction = 0;

    /// <summary>
    /// Priority value for recent file changes.
    /// </summary>
    public const int PriorityRecentChange = 1;

    /// <summary>
    /// Priority value for normal batch operations.
    /// </summary>
    public const int PriorityNormal = 2;

    /// <summary>
    /// Priority value for background indexing (lowest priority).
    /// </summary>
    public const int PriorityBackground = 3;

    /// <summary>
    /// Creates a new queue item with default priority and current timestamp.
    /// </summary>
    /// <param name="projectId">The project to associate the document with.</param>
    /// <param name="filePath">Absolute path to the file to ingest.</param>
    /// <param name="priority">Processing priority (default: <see cref="PriorityNormal"/>).</param>
    /// <param name="correlationId">Optional correlation identifier.</param>
    /// <returns>A new <see cref="IngestionQueueItem"/> instance.</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="filePath"/> is null or whitespace.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// Thrown when <paramref name="priority"/> is negative.
    /// </exception>
    public static IngestionQueueItem Create(
        Guid projectId,
        string filePath,
        int priority = PriorityNormal,
        string? correlationId = null)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            throw new ArgumentException("File path cannot be null or whitespace.", nameof(filePath));
        }

        if (priority < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(priority), priority, "Priority cannot be negative.");
        }

        return new IngestionQueueItem(
            Id: Guid.NewGuid(),
            ProjectId: projectId,
            FilePath: filePath,
            Priority: priority,
            EnqueuedAt: DateTimeOffset.UtcNow,
            CorrelationId: correlationId ?? Guid.NewGuid().ToString("N"));
    }

    /// <summary>
    /// Creates a copy of this item with the specified priority.
    /// </summary>
    /// <param name="newPriority">The new priority value.</param>
    /// <returns>A new <see cref="IngestionQueueItem"/> with updated priority.</returns>
    /// <exception cref="ArgumentOutOfRangeException">
    /// Thrown when <paramref name="newPriority"/> is negative.
    /// </exception>
    public IngestionQueueItem WithPriority(int newPriority)
    {
        if (newPriority < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(newPriority), newPriority, "Priority cannot be negative.");
        }

        return this with { Priority = newPriority };
    }
}
