using Lexichord.Abstractions.Events;
using Lexichord.Abstractions.Messaging;

namespace Lexichord.Tests.Unit.Abstractions.Events;

/// <summary>
/// Unit tests for <see cref="SettingsChangedEvent"/> record.
/// </summary>
[Trait("Category", "Unit")]
public class SettingsChangedEventTests
{
    [Fact]
    public void Constructor_WithRequiredProperties_CreatesValidEvent()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "appearance.theme",
            OldValue = "Dark",
            NewValue = "Light",
            Scope = SettingScope.User,
            ChangedBy = "user-123"
        };

        // Assert
        evt.SettingKey.Should().Be("appearance.theme");
        evt.OldValue.Should().Be("Dark");
        evt.NewValue.Should().Be("Light");
        evt.Scope.Should().Be(SettingScope.User);
        evt.ChangedBy.Should().Be("user-123");
    }

    [Fact]
    public void Event_ImplementsIDomainEvent()
    {
        // Assert
        typeof(SettingsChangedEvent).Should().Implement<IDomainEvent>();
    }

    [Fact]
    public void Event_InheritsFromDomainEventBase()
    {
        // Assert
        typeof(SettingsChangedEvent).Should().BeDerivedFrom<DomainEventBase>();
    }

    [Fact]
    public void Event_WithNewSetting_HasNullOldValue()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "new.setting",
            OldValue = null,
            NewValue = "initial",
            Scope = SettingScope.Application,
            ChangedBy = "system"
        };

        // Assert
        evt.OldValue.Should().BeNull();
        evt.NewValue.Should().Be("initial");
    }

    [Fact]
    public void Event_WithDeletedSetting_HasNullNewValue()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "deprecated.setting",
            OldValue = "old-value",
            NewValue = null,
            Scope = SettingScope.Application,
            ChangedBy = "migration"
        };

        // Assert
        evt.OldValue.Should().Be("old-value");
        evt.NewValue.Should().BeNull();
    }

    [Theory]
    [InlineData(SettingScope.Application)]
    [InlineData(SettingScope.User)]
    [InlineData(SettingScope.Module)]
    [InlineData(SettingScope.Project)]
    [InlineData(SettingScope.Document)]
    public void Event_WithDifferentScopes_StoresScope(SettingScope scope)
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "test.setting",
            Scope = scope,
            ChangedBy = "test-user"
        };

        // Assert
        evt.Scope.Should().Be(scope);
    }

    [Fact]
    public void Event_WithModuleScope_StoresModuleId()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "module.rag.embeddingModel",
            OldValue = "text-embedding-3-small",
            NewValue = "text-embedding-3-large",
            Scope = SettingScope.Module,
            ModuleId = "lexichord.rag",
            ChangedBy = "admin"
        };

        // Assert
        evt.Scope.Should().Be(SettingScope.Module);
        evt.ModuleId.Should().Be("lexichord.rag");
    }

    [Fact]
    public void Event_WithReason_StoresReason()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "database.connectionTimeout",
            OldValue = "30",
            NewValue = "60",
            Scope = SettingScope.Application,
            ChangedBy = "system",
            Reason = "Migration script update"
        };

        // Assert
        evt.Reason.Should().Be("Migration script update");
    }

    [Fact]
    public void Event_IsImmutable()
    {
        // Arrange
        var evt = new SettingsChangedEvent
        {
            SettingKey = "appearance.theme",
            OldValue = "Dark",
            NewValue = "Light",
            Scope = SettingScope.User,
            ChangedBy = "user-123"
        };

        // Act - Create new instance with modified property
        var modified = evt with { NewValue = "System" };

        // Assert - Original unchanged
        evt.NewValue.Should().Be("Light");
        modified.NewValue.Should().Be("System");
    }

    [Fact]
    public void Event_HasAutoGeneratedEventId()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "test.setting",
            Scope = SettingScope.Application,
            ChangedBy = "test"
        };

        // Assert
        evt.EventId.Should().NotBeEmpty();
    }

    [Fact]
    public void Event_HasAutoGeneratedOccurredAt()
    {
        // Arrange & Act
        var evt = new SettingsChangedEvent
        {
            SettingKey = "test.setting",
            Scope = SettingScope.Application,
            ChangedBy = "test"
        };

        // Assert
        evt.OccurredAt.Should().BeCloseTo(DateTimeOffset.UtcNow, TimeSpan.FromSeconds(1));
    }
}
