// =============================================================================
// File: ValidationSummary.cs
// Project: Lexichord.Abstractions
// Description: Summary statistics for validation results.
// =============================================================================
// LOGIC: Provides a compact statistical view of a ValidationResult for
//   dashboard display and reporting. Counts findings by severity, validator,
//   and code, plus tracks fixable findings.
//
// Spec Adaptations:
//   - AutoFixableFindings omitted (SuggestedFix is string?, no CanAutoApply)
//
// v0.6.5i: Validation Result Aggregator (CKVS Phase 3a)
// =============================================================================

namespace Lexichord.Abstractions.Contracts.Knowledge.Validation.Aggregation;

/// <summary>
/// Summary statistics computed from a <see cref="ValidationResult"/>.
/// </summary>
/// <remarks>
/// <para>
/// Generated by <c>ValidationSummaryGenerator.Generate()</c> to provide a
/// compact, pre-computed statistical view suitable for dashboards, status bars,
/// and validation reports.
/// </para>
/// <para>
/// <b>Introduced in:</b> v0.6.5i as part of the Validation Result Aggregator.
/// </para>
/// </remarks>
public record ValidationSummary
{
    /// <summary>
    /// Total number of findings in the result.
    /// </summary>
    public int TotalFindings { get; init; }

    /// <summary>
    /// Finding count grouped by <see cref="ValidationSeverity"/>.
    /// </summary>
    public required IReadOnlyDictionary<ValidationSeverity, int> BySeverity { get; init; }

    /// <summary>
    /// Finding count grouped by validator ID.
    /// </summary>
    public required IReadOnlyDictionary<string, int> ByValidator { get; init; }

    /// <summary>
    /// Finding count grouped by machine-readable finding code.
    /// </summary>
    public required IReadOnlyDictionary<string, int> ByCode { get; init; }

    /// <summary>
    /// Number of findings that have a non-null <see cref="ValidationFinding.SuggestedFix"/>.
    /// </summary>
    public int FixableFindings { get; init; }
}
