// =============================================================================
// File: CanonicalRecord.cs
// Project: Lexichord.Abstractions
// Description: Record representing the authoritative version of a unique fact.
// =============================================================================
// VERSION: v0.5.9c (Canonical Record Management)
// LOGIC: A canonical record points to the "golden" chunk that represents a
//   unique fact. Variants (duplicates) are tracked in ChunkVariants and merged
//   during deduplication, incrementing MergeCount.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.RAG;

/// <summary>
/// Represents the authoritative canonical record for a unique fact in the knowledge base.
/// </summary>
/// <remarks>
/// <para>
/// <b>Introduced in:</b> v0.5.9c as part of the Semantic Memory Deduplication feature.
/// </para>
/// <para>
/// A canonical record identifies the single authoritative chunk that represents a unique fact.
/// When duplicate or equivalent chunks are detected, they are merged into the canonical as
/// variants, and <see cref="MergeCount"/> is incremented to track consolidation.
/// </para>
/// <para>
/// This record maps to the <c>CanonicalRecords</c> table created by Migration_008_CanonicalRecords.
/// </para>
/// </remarks>
/// <param name="Id">
/// The unique identifier for this canonical record.
/// Generated by the database (UUID/GUID) when the record is created.
/// </param>
/// <param name="CanonicalChunkId">
/// The identifier of the authoritative chunk.
/// Foreign key to <see cref="Chunk.Id"/>. This is the "golden" representation of the fact.
/// </param>
/// <param name="CreatedAt">
/// When this canonical record was first established.
/// </param>
/// <param name="UpdatedAt">
/// When this canonical record was last modified (e.g., variant merged or promoted).
/// </param>
/// <param name="MergeCount">
/// The number of variants that have been merged into this canonical record.
/// Incremented each time <see cref="ICanonicalManager.MergeIntoCanonicalAsync"/> is called.
/// </param>
public record CanonicalRecord(
    Guid Id,
    Guid CanonicalChunkId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    int MergeCount)
{
    /// <summary>
    /// Gets or sets the canonical chunk entity.
    /// </summary>
    /// <value>
    /// The full <see cref="Chunk"/> entity, or <c>null</c> if not loaded.
    /// </value>
    /// <remarks>
    /// This navigation property is optionally populated by repository operations
    /// when the caller needs the full chunk content.
    /// </remarks>
    public Chunk? CanonicalChunk { get; init; }

    /// <summary>
    /// Gets whether this canonical record has any merged variants.
    /// </summary>
    /// <value>
    /// <c>true</c> if <see cref="MergeCount"/> is greater than zero; otherwise, <c>false</c>.
    /// </value>
    public bool HasVariants => MergeCount > 0;

    /// <summary>
    /// Creates a new canonical record for an initial chunk (no variants yet).
    /// </summary>
    /// <param name="chunkId">The chunk to establish as canonical.</param>
    /// <returns>A new <see cref="CanonicalRecord"/> ready for storage.</returns>
    /// <remarks>
    /// The <see cref="Id"/> is set to <see cref="Guid.Empty"/> (database assigns),
    /// timestamps are set to current time, and <see cref="MergeCount"/> is zero.
    /// </remarks>
    public static CanonicalRecord CreateForChunk(Guid chunkId)
    {
        var now = DateTimeOffset.UtcNow;
        return new CanonicalRecord(
            Id: Guid.Empty,
            CanonicalChunkId: chunkId,
            CreatedAt: now,
            UpdatedAt: now,
            MergeCount: 0);
    }
}
