// =============================================================================
// File: ChunkVariant.cs
// Project: Lexichord.Abstractions
// Description: Record representing a chunk merged as a variant into a canonical.
// =============================================================================
// VERSION: v0.5.9c (Canonical Record Management)
// LOGIC: When deduplication identifies equivalent or related chunks, they are
//   merged as variants under a canonical record. This preserves the relationship
//   type and similarity score for auditing and potential variant promotion.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.RAG;

/// <summary>
/// Represents a chunk that has been merged as a variant into a canonical record.
/// </summary>
/// <remarks>
/// <para>
/// <b>Introduced in:</b> v0.5.9c as part of the Semantic Memory Deduplication feature.
/// </para>
/// <para>
/// When a chunk is identified as equivalent or related to an existing canonical record,
/// it is stored as a variant. The original chunk remains in the Chunks table, but is
/// linked to the canonical for deduplication purposes. Variants can later be:
/// </para>
/// <list type="bullet">
///   <item><description>Promoted to canonical via <see cref="ICanonicalManager.PromoteVariantAsync"/></description></item>
///   <item><description>Detached via <see cref="ICanonicalManager.DetachVariantAsync"/></description></item>
/// </list>
/// <para>
/// This record maps to the <c>ChunkVariants</c> table created by Migration_008_CanonicalRecords.
/// </para>
/// </remarks>
/// <param name="Id">
/// The unique identifier for this variant record.
/// Generated by the database (UUID/GUID) when the variant is merged.
/// </param>
/// <param name="CanonicalRecordId">
/// The identifier of the parent canonical record.
/// Foreign key to <see cref="CanonicalRecord.Id"/>.
/// </param>
/// <param name="VariantChunkId">
/// The identifier of the variant chunk.
/// Foreign key to <see cref="Chunk.Id"/>. This chunk is considered a duplicate of the canonical.
/// </param>
/// <param name="RelationshipType">
/// The semantic relationship between the variant and the canonical chunk.
/// Determined by <see cref="IRelationshipClassifier"/> during deduplication.
/// </param>
/// <param name="SimilarityScore">
/// The cosine similarity score between variant and canonical embeddings.
/// Range: 0.0 to 1.0, where 1.0 indicates identical vectors.
/// </param>
/// <param name="MergedAt">
/// When this variant was merged into the canonical record.
/// </param>
public record ChunkVariant(
    Guid Id,
    Guid CanonicalRecordId,
    Guid VariantChunkId,
    RelationshipType RelationshipType,
    float SimilarityScore,
    DateTimeOffset MergedAt)
{
    /// <summary>
    /// Gets or sets the variant chunk entity.
    /// </summary>
    /// <value>
    /// The full <see cref="Chunk"/> entity, or <c>null</c> if not loaded.
    /// </value>
    /// <remarks>
    /// This navigation property is optionally populated by repository operations
    /// when the caller needs the full chunk content.
    /// </remarks>
    public Chunk? Chunk { get; init; }

    /// <summary>
    /// Creates a new variant record for merging a chunk into a canonical.
    /// </summary>
    /// <param name="canonicalRecordId">The canonical record to merge into.</param>
    /// <param name="variantChunkId">The chunk being merged as a variant.</param>
    /// <param name="relationshipType">The classified relationship type.</param>
    /// <param name="similarityScore">The similarity score from detection.</param>
    /// <returns>A new <see cref="ChunkVariant"/> ready for storage.</returns>
    /// <remarks>
    /// The <see cref="Id"/> is set to <see cref="Guid.Empty"/> (database assigns),
    /// and <see cref="MergedAt"/> is set to the current time.
    /// </remarks>
    public static ChunkVariant Create(
        Guid canonicalRecordId,
        Guid variantChunkId,
        RelationshipType relationshipType,
        float similarityScore)
    {
        return new ChunkVariant(
            Id: Guid.Empty,
            CanonicalRecordId: canonicalRecordId,
            VariantChunkId: variantChunkId,
            RelationshipType: relationshipType,
            SimilarityScore: similarityScore,
            MergedAt: DateTimeOffset.UtcNow);
    }
}
