// =============================================================================
// File: ChunkProvenance.cs
// Project: Lexichord.Abstractions
// Description: Record tracking the origin and verification of a chunk.
// =============================================================================
// VERSION: v0.5.9c (Canonical Record Management)
// LOGIC: Provenance tracks where a chunk came from (source document, location)
//   and when/by whom it was verified. Critical for audit trails and trust.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.RAG;

/// <summary>
/// Records the origin and verification status of a chunk.
/// </summary>
/// <remarks>
/// <para>
/// <b>Introduced in:</b> v0.5.9c as part of the Semantic Memory Deduplication feature.
/// </para>
/// <para>
/// Provenance information helps establish trust in the knowledge base by tracking:
/// </para>
/// <list type="bullet">
///   <item><description>Which document the chunk originated from</description></item>
///   <item><description>The specific location within that document</description></item>
///   <item><description>When the chunk was ingested and by whom it was verified</description></item>
/// </list>
/// <para>
/// This record maps to the <c>ChunkProvenance</c> table created by Migration_008_CanonicalRecords.
/// </para>
/// </remarks>
/// <param name="Id">
/// The unique identifier for this provenance record.
/// Generated by the database (UUID/GUID) when the record is created.
/// </param>
/// <param name="ChunkId">
/// The identifier of the chunk this provenance describes.
/// Foreign key to <see cref="Chunk.Id"/>.
/// </param>
/// <param name="SourceDocumentId">
/// The identifier of the source document, if known.
/// Foreign key to Document.Id. May be null for externally-sourced chunks.
/// </param>
/// <param name="SourceLocation">
/// A human-readable description of where in the document the chunk originated.
/// Examples: "Section 3.2", "Page 15, Paragraph 2", "lines 45-67".
/// </param>
/// <param name="IngestedAt">
/// When this chunk was first ingested into the system.
/// </param>
/// <param name="VerifiedAt">
/// When this chunk's content was verified as accurate, if applicable.
/// Null if not yet verified.
/// </param>
/// <param name="VerifiedBy">
/// The user or process that verified this chunk's content.
/// Null if not yet verified.
/// </param>
public record ChunkProvenance(
    Guid Id,
    Guid ChunkId,
    Guid? SourceDocumentId,
    string? SourceLocation,
    DateTimeOffset IngestedAt,
    DateTimeOffset? VerifiedAt,
    string? VerifiedBy)
{
    /// <summary>
    /// Gets whether this chunk has been verified.
    /// </summary>
    /// <value>
    /// <c>true</c> if <see cref="VerifiedAt"/> is not null; otherwise, <c>false</c>.
    /// </value>
    public bool IsVerified => VerifiedAt.HasValue;

    /// <summary>
    /// Gets whether the source document is known.
    /// </summary>
    /// <value>
    /// <c>true</c> if <see cref="SourceDocumentId"/> is not null; otherwise, <c>false</c>.
    /// </value>
    public bool HasKnownSource => SourceDocumentId.HasValue;

    /// <summary>
    /// Creates a new provenance record for a chunk.
    /// </summary>
    /// <param name="chunkId">The chunk to record provenance for.</param>
    /// <param name="sourceDocumentId">The source document, if known.</param>
    /// <param name="sourceLocation">The location within the document.</param>
    /// <returns>A new <see cref="ChunkProvenance"/> ready for storage.</returns>
    /// <remarks>
    /// The <see cref="Id"/> is set to <see cref="Guid.Empty"/> (database assigns),
    /// <see cref="IngestedAt"/> is set to the current time, and verification fields are null.
    /// </remarks>
    public static ChunkProvenance Create(
        Guid chunkId,
        Guid? sourceDocumentId = null,
        string? sourceLocation = null)
    {
        return new ChunkProvenance(
            Id: Guid.Empty,
            ChunkId: chunkId,
            SourceDocumentId: sourceDocumentId,
            SourceLocation: sourceLocation,
            IngestedAt: DateTimeOffset.UtcNow,
            VerifiedAt: null,
            VerifiedBy: null);
    }

    /// <summary>
    /// Creates a verified copy of this provenance record.
    /// </summary>
    /// <param name="verifiedBy">The user or process performing verification.</param>
    /// <returns>A new <see cref="ChunkProvenance"/> with verification timestamp set.</returns>
    public ChunkProvenance WithVerification(string verifiedBy)
    {
        return this with
        {
            VerifiedAt = DateTimeOffset.UtcNow,
            VerifiedBy = verifiedBy
        };
    }
}
