// =============================================================================
// File: Contradiction.cs
// Project: Lexichord.Abstractions
// Description: Record representing a detected contradiction between chunks.
// =============================================================================
// VERSION: v0.5.9e (Contradiction Detection & Resolution)
// LOGIC: Captures the complete state of a detected contradiction, including
//   the conflicting chunks, classification confidence, lifecycle status,
//   and resolution details when applicable.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.RAG;

/// <summary>
/// Represents a detected contradiction between two chunks of content.
/// </summary>
/// <remarks>
/// <para>
/// <b>Introduced in:</b> v0.5.9e as part of the Semantic Memory Deduplication feature.
/// </para>
/// <para>
/// A contradiction is detected when the <see cref="IRelationshipClassifier"/> identifies
/// two similar chunks as containing conflicting information. This record tracks:
/// </para>
/// <list type="bullet">
///   <item><description>The two conflicting chunk identifiers.</description></item>
///   <item><description>Classification metadata (similarity, confidence, reason).</description></item>
///   <item><description>Lifecycle status (pending, under review, resolved).</description></item>
///   <item><description>Resolution details when applicable.</description></item>
/// </list>
/// <para>
/// This record maps to the <c>contradictions</c> table in the database.
/// </para>
/// </remarks>
/// <param name="Id">
/// Unique identifier for this contradiction record.
/// Generated by the database when the contradiction is stored.
/// </param>
/// <param name="ChunkAId">
/// The identifier of the first conflicting chunk.
/// Typically the existing chunk that was found during similarity detection.
/// </param>
/// <param name="ChunkBId">
/// The identifier of the second conflicting chunk.
/// Typically the newly ingested chunk that triggered the contradiction detection.
/// </param>
/// <param name="SimilarityScore">
/// The cosine similarity score between the two chunks (0.0 to 1.0).
/// Provided by <see cref="ISimilarityDetector"/> during the deduplication pipeline.
/// </param>
/// <param name="ClassificationConfidence">
/// The confidence level of the contradiction classification (0.0 to 1.0).
/// Provided by <see cref="IRelationshipClassifier"/> indicating certainty
/// that the relationship is contradictory.
/// </param>
/// <param name="ContradictionReason">
/// A human-readable explanation of why these chunks are contradictory.
/// May be provided by LLM classification or rule-based heuristics.
/// </param>
/// <param name="Status">
/// The current lifecycle status of this contradiction.
/// See <see cref="ContradictionStatus"/> for possible values.
/// </param>
/// <param name="DetectedAt">
/// UTC timestamp when the contradiction was first detected.
/// </param>
/// <param name="DetectedBy">
/// The source of the detection. Typically "DeduplicationService" for automatic
/// detection, or a user identifier for manually flagged contradictions.
/// </param>
/// <param name="ProjectId">
/// Optional project scope for multi-tenant filtering.
/// When null, the contradiction applies globally.
/// </param>
/// <param name="ReviewedBy">
/// The identity of the admin who reviewed this contradiction.
/// Null if not yet reviewed.
/// </param>
/// <param name="ReviewedAt">
/// UTC timestamp when the contradiction was reviewed.
/// Null if not yet reviewed.
/// </param>
/// <param name="Resolution">
/// The resolution decision applied to this contradiction.
/// Null if not yet resolved.
/// </param>
public record Contradiction(
    Guid Id,
    Guid ChunkAId,
    Guid ChunkBId,
    float SimilarityScore,
    float ClassificationConfidence,
    string? ContradictionReason,
    ContradictionStatus Status,
    DateTimeOffset DetectedAt,
    string DetectedBy,
    Guid? ProjectId = null,
    string? ReviewedBy = null,
    DateTimeOffset? ReviewedAt = null,
    ContradictionResolution? Resolution = null)
{
    /// <summary>
    /// Gets whether this contradiction has been resolved.
    /// </summary>
    /// <value><c>true</c> if <see cref="Status"/> is <see cref="ContradictionStatus.Resolved"/>.</value>
    public bool IsResolved => Status == ContradictionStatus.Resolved;

    /// <summary>
    /// Gets whether this contradiction is still pending action.
    /// </summary>
    /// <value><c>true</c> if <see cref="Status"/> is <see cref="ContradictionStatus.Pending"/>.</value>
    public bool IsPending => Status == ContradictionStatus.Pending;

    /// <summary>
    /// Gets whether this contradiction is a terminal state (no further action needed).
    /// </summary>
    /// <value>
    /// <c>true</c> if <see cref="Status"/> is <see cref="ContradictionStatus.Resolved"/>,
    /// <see cref="ContradictionStatus.Dismissed"/>, or <see cref="ContradictionStatus.AutoResolved"/>.
    /// </value>
    public bool IsTerminal =>
        Status is ContradictionStatus.Resolved
            or ContradictionStatus.Dismissed
            or ContradictionStatus.AutoResolved;

    /// <summary>
    /// Gets whether the classification has high confidence.
    /// </summary>
    /// <value><c>true</c> if <see cref="ClassificationConfidence"/> is >= 0.8.</value>
    public bool HasHighConfidence => ClassificationConfidence >= 0.8f;

    /// <summary>
    /// Creates a new contradiction record for detection.
    /// </summary>
    /// <param name="chunkAId">The first conflicting chunk ID.</param>
    /// <param name="chunkBId">The second conflicting chunk ID.</param>
    /// <param name="similarityScore">Similarity between the chunks.</param>
    /// <param name="confidence">Classification confidence.</param>
    /// <param name="reason">Optional explanation of the contradiction.</param>
    /// <param name="detectedBy">Source of the detection.</param>
    /// <param name="projectId">Optional project scope.</param>
    /// <returns>A new <see cref="Contradiction"/> in <see cref="ContradictionStatus.Pending"/> state.</returns>
    public static Contradiction Create(
        Guid chunkAId,
        Guid chunkBId,
        float similarityScore,
        float confidence,
        string? reason = null,
        string detectedBy = "DeduplicationService",
        Guid? projectId = null)
    {
        return new Contradiction(
            Id: Guid.Empty, // Database assigns
            ChunkAId: chunkAId,
            ChunkBId: chunkBId,
            SimilarityScore: similarityScore,
            ClassificationConfidence: confidence,
            ContradictionReason: reason,
            Status: ContradictionStatus.Pending,
            DetectedAt: DateTimeOffset.UtcNow,
            DetectedBy: detectedBy,
            ProjectId: projectId);
    }
}
