// =============================================================================
// File: Document.cs
// Project: Lexichord.Abstractions
// Description: Record representing an indexed document in the RAG system.
// =============================================================================
// LOGIC: Immutable record for thread-safe document metadata storage.
//   - Maps to the 'documents' table created by Migration_003_VectorSchema.
//   - Hash is used for change detection (SHA-256 of file content).
//   - FailureReason is only populated when Status == Failed.
// =============================================================================

namespace Lexichord.Abstractions.Contracts.RAG;

/// <summary>
/// Represents an indexed document in the RAG (Retrieval-Augmented Generation) system.
/// </summary>
/// <remarks>
/// <para>
/// This record corresponds to a row in the <c>documents</c> table and serves as the
/// parent entity for <see cref="Chunk"/> records. Each document is uniquely identified
/// by its <see cref="FilePath"/> within a <see cref="ProjectId"/>.
/// </para>
/// <para>
/// The <see cref="Hash"/> property enables efficient change detection: when the file
/// watcher detects a modification, comparing hashes determines whether re-indexing
/// is necessary.
/// </para>
/// </remarks>
/// <param name="Id">
/// The unique identifier for this document.
/// Generated by the database (UUID/GUID) when the document is first added.
/// </param>
/// <param name="ProjectId">
/// The identifier of the project this document belongs to.
/// Used to scope queries and enforce project-level isolation.
/// </param>
/// <param name="FilePath">
/// The relative path to the source file within the project.
/// Combined with <paramref name="ProjectId"/>, this forms a unique key.
/// </param>
/// <param name="Title">
/// A human-readable title for the document.
/// Typically derived from the filename or extracted from document metadata.
/// </param>
/// <param name="Hash">
/// SHA-256 hash of the file content at the time of indexing.
/// Used for change detection to identify stale documents.
/// </param>
/// <param name="Status">
/// The current lifecycle status of this document.
/// See <see cref="DocumentStatus"/> for the complete state machine.
/// </param>
/// <param name="IndexedAt">
/// The UTC timestamp when this document was last successfully indexed.
/// Null if the document has never been indexed (<see cref="DocumentStatus.Pending"/>)
/// or if indexing failed (<see cref="DocumentStatus.Failed"/>).
/// </param>
/// <param name="FailureReason">
/// Diagnostic information explaining why indexing failed.
/// Only populated when <paramref name="Status"/> is <see cref="DocumentStatus.Failed"/>.
/// </param>
public record Document(
    Guid Id,
    Guid ProjectId,
    string FilePath,
    string Title,
    string Hash,
    DocumentStatus Status,
    DateTime? IndexedAt,
    string? FailureReason)
{
    /// <summary>
    /// Creates a new document in the <see cref="DocumentStatus.Pending"/> state.
    /// </summary>
    /// <param name="projectId">The project this document belongs to.</param>
    /// <param name="filePath">The relative path to the source file.</param>
    /// <param name="title">A human-readable title for the document.</param>
    /// <param name="hash">SHA-256 hash of the current file content.</param>
    /// <returns>A new <see cref="Document"/> ready for indexing.</returns>
    /// <remarks>
    /// This factory method sets sensible defaults for new documents:
    /// <list type="bullet">
    ///   <item><description><see cref="Id"/> is set to <see cref="Guid.Empty"/> (database will assign).</description></item>
    ///   <item><description><see cref="Status"/> is set to <see cref="DocumentStatus.Pending"/>.</description></item>
    ///   <item><description><see cref="IndexedAt"/> is null (not yet indexed).</description></item>
    ///   <item><description><see cref="FailureReason"/> is null (no failure).</description></item>
    /// </list>
    /// </remarks>
    public static Document CreatePending(Guid projectId, string filePath, string title, string hash)
    {
        return new Document(
            Id: Guid.Empty,
            ProjectId: projectId,
            FilePath: filePath,
            Title: title,
            Hash: hash,
            Status: DocumentStatus.Pending,
            IndexedAt: null,
            FailureReason: null);
    }
}
